"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var heladeraSmart_1 = require("./heladeraSmart");
var moduloWifi_1 = require("./moduloWifi");
var moduloWifi1 = new moduloWifi_1.moduloWifi(600, 100);
var heladeraSmart1 = new heladeraSmart_1.heladeraSmart('electrolux', 'ggwp', false, 0, moduloWifi1);
heladeraSmart1.mostrarInfo();
console.log("------------------------------------------------------");
console.log('encendido:');
console.log(heladeraSmart1.estaEncendido);
heladeraSmart1.encender();
console.log('encendido:');
console.log(heladeraSmart1.estaEncendido);
console.log("------------------------------------------------------");
console.log('temperatura:');
console.log(heladeraSmart1.temperatura);
heladeraSmart1.cambiarTemperatura();
console.log('temperatura:');
console.log(heladeraSmart1.temperatura);
console.log("------------------------------------------------------");
heladeraSmart1.conectarseWifi();
console.log("------------------------------------------------------");
heladeraSmart1.mostrarInfo();
